[theme]
primaryColor = "#4299e1"
backgroundColor = "#1e3a5f" 
secondaryBackgroundColor = "#1e3a5f"
textColor = "#ffffff"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true